# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        registry-url: "https://npm.pkg.github.com"
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
    - name: Install dependencies
      run: |
        yarn add yup
        yarn add crypto-js
        yarn install
        
    - name: Build page
      run: yarn build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: shared
        path: ./dist

  deploy_server_dev:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: shared

      - name: Deploy to server 
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: '${{ secrets.FTP_HOST_SBAS_WEB }}'
          port: 22
          username: ${{ secrets.FTP_USER_SBAS_WEB }}
          password: ${{ secrets.FTP_PW_SBAS_WEB }}
          local_path: './dist'
          remote_path: '/C:/www/dev.smartbas.org'
          sftp_only: true
          sftpArgs: '-o ConnectTimeout=5'

  deploy_server2_test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: shared

      - name: Deploy to server 2
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: '${{ secrets.FTP_HOST_SBAS_WEB }}'
          port: 22
          username: ${{ secrets.FTP_USER_SBAS_WEB }}
          password: ${{ secrets.FTP_PW_SBAS_WEB }}
          local_path: './dist'
          remote_path: '/C:/www/test.smartbas.org'
          sftp_only: true
          sftpArgs: '-o ConnectTimeout=5'
